project:
  type: website
  output-dir: docs

website:
  title: "Oficina"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Programação
        href: programacao.qmd
      - text: Material de apoio
        href: mat_apoio.qmd
    right:
      - text: Organização
        href: organizacao.qmd
      - icon: instagram
        href: https://www.instagram.com/icmbio.cemave/
      - icon: youtube
        href: https://www.youtube.com/@CEMAVEICMBio
    background: "#2780e3"
    
  page-footer:
    center: |
      [Fale conosco - CEMAVE](mailto:cemave.sede@icmbio.gov.br)
    left: |
      Made with [Quarto](https://quarto.org/)
    background: "#2780e3"
        
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

